apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-app
  namespace: prod
automountServiceAccountToken: false


---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prod-app-role
  namespace: prod
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get","watch","list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list"]  
  

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-app-rolebinding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: prod-app
  namespace: prod
roleRef:
  kind: Role
  name: prod-app-role
  apiGroup: rbac.authorization.k8s.io 
  
